FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache bash

COPY package*.json ./
RUN npm install -g truffle
RUN npm install

COPY . .

RUN chmod +x wait-for-it.sh entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]